In [1]:
import numpy as np

In [2]:
np.zeros(0)

array([], dtype=float64)

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 9)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [9]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a[2] = 10

In [12]:
a

array([ 1,  2, 10,  4])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [19]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [20]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [27]:
n[0,1] = 10
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [28]:
n[0]

array([ 1, 10,  3])

In [32]:
n[0] = [1,1,1]
n

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
n[:, 1]

array([1, 5, 8])

In [35]:
n[:, 2]

array([1, 6, 9])

In [36]:
n[:, 2] = [0,1,2]
n

array([[1, 1, 0],
       [4, 5, 1],
       [7, 8, 2]])

In [42]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [45]:
np.random.seed(2)
-100*np.random.randn(5, 2)

array([[  41.67578474,    5.62668272],
       [ 213.61960957, -164.02708084],
       [ 179.34355852,   84.17473657],
       [ -50.28814172,  124.52880866],
       [ 105.79522189,   90.90076149]])

In [49]:
np.random.seed(2)
np.random.randint(low =0, high =100, size =(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [51]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [52]:
a + 1

array([1, 2, 3, 4, 5])

In [53]:
a * 2

array([0, 2, 4, 6, 8])

In [56]:
b = (10 + (a * 2)) ** 2 / 100

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [57]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [58]:
a ** b

array([ 0.        ,  1.        ,  3.89061979, 16.6506201 , 89.26359465])

In [59]:
a >= 2

array([False, False,  True,  True,  True])

In [60]:
a > b

array([False, False,  True,  True,  True])

In [61]:
a[a>b]

array([2, 3, 4])

In [62]:
a.min()

np.int64(0)

In [63]:
a.max()

np.int64(4)

In [64]:
a.sum()

np.int64(10)

In [65]:
a.mean()

np.float64(2.0)

In [66]:
a.std()

np.float64(1.4142135623730951)

In [67]:
n.sum()

np.int64(29)